version: '3'
services:
  mssql:
    # https://hub.docker.com/_/microsoft-mssql-server
    # https://docs.microsoft.com/en-us/sql/linux/quickstart-install-connect-docker?view=sql-server-ver15&pivots=cs1-bash
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "Denteriarlly8!"
      ACCEPT_EULA: "Y"
      MSSQL_PATH: /opt/mssql-tools/bin
